---
title: "timecourse"
author: "Becca Belmonte"
date: "2022-11-22"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Libraries
```{r message=FALSE, warning=FALSE}
# Scripts for differential expression analyses
# pairwise differential expression

# BiocManager::install("clusterProfiler")
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("pathview")
# BiocManager::install("enrichplot")
library(clusterProfiler)
library(enrichplot)
library(ggplot2)

organism = "org.Dm.eg.db"
#BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)
library(tidyverse)
library(limma)
library(edgeR)
library(splines)
library(DESeq2)
library(fgsea)
library(ggrepel)
select <- dplyr::select

colors_sex <- c("#D3C164", "#05366E")
```


# Import
```{r}
fpkm_counts <- read.csv("RNA_seq/Data/fpkm_gene.csv")
rownames(fpkm_counts) <- fpkm_counts$gene_name
dat_fpkm <- fpkm_counts %>% 
  dplyr::select(-c(X, gene_id, source, gene_name, gene_biotype, phase))

full_counts <- read.csv("RNA_seq/Data/raw_gene.csv")
rownames(full_counts) <- full_counts$gene_name
dat <- full_counts %>% 
  dplyr::select(-c(X, gene_id, source, gene_name, gene_biotype, phase))

col_data <- read.csv("RNA_seq/Data/col_data_for_r.csv")
rownames(col_data) <- col_data$ID
gene_names_fb <- fpkm_counts %>% 
  dplyr::select(gene_id, gene_name)

```


# Making models

```{r}
# Larval hemocytes
dat_fpkm_lar <- dat_fpkm %>% 
  select(contains("lar"))

col_data_lar <- col_data %>% 
  filter(Stage == "larvae" & Tissue == "hemocyte")

dat_fpkm_lar <- dat_fpkm_lar %>% 
  select(col_data_lar$ID)
data_lar_colnames <- colnames(dat_fpkm_lar)
colnames(dat_fpkm_lar) <- col_data_lar$Sex

# dimorphically expressed at baseline
lev <- unique(colnames(dat_fpkm_lar))
f <- factor(col_data_lar$Sex, levels = lev)
design <- model.matrix(~0+f)
colnames(design) <- lev
fit <- lmFit(dat_fpkm_lar, design)

# Which genes respond at either the 2 hour or 4 hour time?
cont_lar <- makeContrasts(
  "Male-Female",
  levels = design
)
fit_lar <- contrasts.fit(fit, cont_lar)
fit_lar <- eBayes(fit_lar)
top_lar <- topTable(fit_lar, adjust = "BH", number = 17412)

# differentially expressed over time (ignoring sex)
lev <- c("UC", "Hr_2", "Hr_4")
f <- factor(col_data_hem$time_chr, levels = lev)
design <- model.matrix(~0+f)
colnames(design) <- lev
fit <- lmFit(dat_fpkm_time, design)

############################################################
# Setting up the adult hemocyte model

dat_fpkm_hem <- dat_fpkm %>% 
  select(contains("hem"))

col_data_hem <- col_data %>% 
  filter(Stage == "adult" & Tissue == "hemocyte") %>% 
  mutate(time = gsub("_hr", "", Time_post_inf)) %>% 
  mutate(time = case_when(time == "UC" ~ 0,
                          time == "2" ~ 2,
                          time == "4" ~ 4),
         time_chr = case_when(Time_post_inf == "UC" ~ "UC",
                          Time_post_inf == "2_hr" ~ "Hr_2",
                          Time_post_inf == "4_hr" ~ "Hr_4")) %>% 
  mutate(group = paste(Sex, time, sep = "_"))

dat_fpkm_hem <- dat_fpkm_hem %>% 
  select(col_data_hem$ID)
data_colnames <- colnames(dat_fpkm_hem)
dat_fpkm_time <- dat_fpkm_hem
colnames(dat_fpkm_time) <- col_data_hem$time_chr

# dimorphically expressed at baseline
col_data_hem_0 <- col_data_hem %>% 
  filter(time == 0)
dat_fpkm_hem_0 <- dat_fpkm_hem %>% 
  select(col_data_hem_0$ID)
data_colnames_0 <- colnames(dat_fpkm_hem_0)
colnames(dat_fpkm_hem_0) <- col_data_hem_0$Sex
lev <- unique(colnames(dat_fpkm_hem_0))
f <- factor(col_data_hem_0$Sex, levels = lev)
design <- model.matrix(~0+f)
colnames(design) <- lev
fit <- lmFit(dat_fpkm_hem_0, design)

# Which genes are dimorphic at 0 hours?
cont_sex_0 <- makeContrasts(
  "Male-Female",
  levels = design
)
fit_sex_0 <- contrasts.fit(fit, cont_sex_0)
fit_sex_0 <- eBayes(fit_sex_0)
top_sex_0 <- topTable(fit_sex_0, adjust = "BH", number = 17412)

# dimorphically expressed at 2 hr
col_data_hem_2 <- col_data_hem %>% 
  filter(time == 2)
dat_fpkm_hem_2 <- dat_fpkm_hem %>% 
  select(col_data_hem_2$ID)
data_colnames_2 <- colnames(dat_fpkm_hem_2)
colnames(dat_fpkm_hem_2) <- col_data_hem_2$Sex
lev <- unique(colnames(dat_fpkm_hem_2))
f <- factor(col_data_hem_2$Sex, levels = lev)
design <- model.matrix(~0+f)
colnames(design) <- lev
fit <- lmFit(dat_fpkm_hem_2, design)

# Which genes are dimorphic at 2 hours?
cont_sex_2 <- makeContrasts(
  "Male-Female",
  levels = design
)
fit_sex_2 <- contrasts.fit(fit, cont_sex_2)
fit_sex_2 <- eBayes(fit_sex_2)
top_sex_2 <- topTable(fit_sex_2, adjust = "BH", number = 17412)

# dimorphically expressed at 4 hr
col_data_hem_4 <- col_data_hem %>% 
  filter(time == 4)
dat_fpkm_hem_4 <- dat_fpkm_hem %>% 
  select(col_data_hem_4$ID)
data_colnames_4 <- colnames(dat_fpkm_hem_4)
colnames(dat_fpkm_hem_4) <- col_data_hem_4$Sex
lev <- unique(colnames(dat_fpkm_hem_4))
f <- factor(col_data_hem_4$Sex, levels = lev)
design <- model.matrix(~0+f)
colnames(design) <- lev
fit <- lmFit(dat_fpkm_hem_4, design)

# Which genes are dimorphic at 4 hours?
cont_sex_4 <- makeContrasts(
  "Male-Female",
  levels = design
)
fit_sex_4 <- contrasts.fit(fit, cont_sex_4)
fit_sex_4 <- eBayes(fit_sex_4)
top_sex_4 <- topTable(fit_sex_4, adjust = "BH", number = 17412)

# dimorphically expressed ignoring time
dat_fpkm_hem_dim <- dat_fpkm_hem %>% 
  select(col_data_hem$ID)
data_colnames_hem_dim <- colnames(dat_fpkm_hem_dim)
colnames(dat_fpkm_hem_dim) <- col_data_hem$Sex
lev <- unique(colnames(dat_fpkm_hem_dim))
f <- factor(col_data_hem$Sex, levels = lev)
design <- model.matrix(~0+f)
colnames(design) <- lev
fit <- lmFit(dat_fpkm_hem_dim, design)

# Which genes are dimorphic ignoring time?
cont_sex <- makeContrasts(
  "Male-Female",
  levels = design
)
fit_sex <- contrasts.fit(fit, cont_sex)
fit_sex <- eBayes(fit_sex)
top_sex <- topTable(fit_sex, adjust = "BH", number = 17412)

# differentially expressed over time (ignoring time)
lev <- c("UC", "Hr_2", "Hr_4")
f <- factor(col_data_hem$time_chr, levels = lev)
design <- model.matrix(~0+f)
colnames(design) <- lev
fit <- lmFit(dat_fpkm_time, design)

# Which genes respond at either the 2 hour or 4 hour time?
cont_time <- makeContrasts(
  "Hr_2-UC",
  "Hr_4-Hr_2",
  levels = design
)
fit_time <- contrasts.fit(fit, cont_time)
fit_time <- eBayes(fit_time)
top_time <- topTable(fit_time, adjust = "BH", number = 17412)




lev <- c("Female_0", "Male_0", "Male_2", "Female_2", "Female_4", "Male_4")
f <- factor(col_data_hem$group, levels = lev)
design <- model.matrix(~0+f)
colnames(design) <- lev
fit <- lmFit(dat_fpkm_hem, design)

# Which genes respond at either the 2 hour or 4 hour time in females?
cont_female <- makeContrasts(
  "Female_2-Female_0",
  "Female_4-Female_2",
  levels = design
)
fit_female <- contrasts.fit(fit, cont_female)
fit_female <- eBayes(fit_female)
top_female <- topTable(fit_female, adjust = "BH", number = 17412)

# Which genes respond at either the 2 hour or 4 hour time in males?
cont_male <- makeContrasts(
  "Male_2-Male_0",
  "Male_4-Male_2",
  levels = design
)
fit_male <- contrasts.fit(fit, cont_male)
fit_male <- eBayes(fit_male)
top_male <- topTable(fit_male, adjust = "BH", number = 17412) 

# Which genes respond differently over time in females relative to males?
cont.dif <- makeContrasts(
  dif2hr = (Male_2-Male_0)-(Female_2-Female_0),
  dif4hr = (Male_4-Male_0)-(Female_4-Female_0),
  levels = design
)

fit_dif <- contrasts.fit(fit, cont.dif)
fit_dif <- eBayes(fit_dif)
top_dif <- topTable(fit_dif, adjust.method = "BH", sort.by = "B", resort.by = NULL, p.value = 1, lfc = 0, confint = FALSE, number = 17412)
```


# Visualizations
## Both
```{r}
top_time$gene <- rownames(top_time)

top_genes_time <- top_time %>% 
  filter(adj.P.Val < 0.01) %>% 
  filter(AveExpr > 10)

gg_top_time <- dat_fpkm_time
colnames(gg_top_time) <- data_colnames
gg_top_time <- gg_top_time %>% 
  mutate(gene = rownames(gg_top_time)) %>% 
  filter(gene %in% top_genes_time$gene) %>% 
  select(-gene)

library(heatmap3)
library(viridis)
library(gridGraphics)
colors <- colorRampPalette( viridis(9) )(28236)


mat_top_time <- as.matrix(gg_top_time)

mat_top_time <- mat_top_time - rowMeans(mat_top_time)

# heatmap3(mat_top_time, trace = "none", col = colors, labCol = NULL, labRow = rownames(mat_top_time), RowSideLabs = F, ColSideLabs = F, mar = c(5, 12), key.title = "Expression", cexRow = 1, scale = "row")
# grid.echo()
# top_time_heatmap <- grid.grab()
# 
# png(filename = "Results/top_time_heatmap.png", width = 1000, height = 2000, units = "px")
# grid.draw(top_time_heatmap)
# dev.off()


# library(heatmaply)
# 
# (heat_time <- heatmaply(mat_top_dif, xlab = "", ylab = "", main = "", scale = "column",
#           margins = c(60,100,40,20), 
#           grid_width = 0.00001, titleX = FALSE,
#           hide_colorbar = TRUE, branches_lwd = 0.1, 
#           label_names = c("Gene", "Sample", "Value"),
#           fontsize_row = 10, fontsize_col = 10,
#           labCol = colnames(mat_top_dif),
#           labRow = rownames(mat_top_dif),
#           heatmap_layers = theme(axis.line = element_blank())))

colnames(dat_fpkm_time) <- data_colnames
top_time_gg <- top_time %>% 
  mutate(direction_2 = case_when(Hr_2.UC <0 ~ "2h_neg",
                                 Hr_2.UC >0 ~ "2h_pos"),
         direction_4 = case_when(Hr_4.Hr_2 <0 ~ "4h_neg",
                                 Hr_4.Hr_2 >0 ~ "4h_pos")) %>% 
  select(gene, direction_2, direction_4) %>% 
  mutate(direction = paste(direction_2, direction_4))


gg_top_time <- dat_fpkm_time %>% 
  mutate(gene = rownames(dat_fpkm_time)) %>% 
  inner_join(top_time_gg, by = "gene") %>% 
  pivot_longer(cols = 1:14, names_to = "sample", values_to = "count") %>% 
  separate(sample, into = c("Sex", "Time", "hem", "rep")) %>% 
  mutate(time_hours = case_when(Time == "2h" ~ 2,
                                Time == "4h" ~ 4,
                                Time == "UC" ~ 0)) %>% 
  group_by(Sex, time_hours, gene) %>% 
  mutate(avg_count = mean(count)) %>% 
  filter(direction %in% c("2h_neg 4h_neg", "2h_neg 4h_pos", "2h_pos 4h_neg", "2h_pos 4h_pos"))

# (time_plot <- ggplot(gg_top_time, aes(x = time_hours, y = avg_count, color = gene)) +
#   geom_line() +
#   geom_point(aes(y = count)) +
#   theme_bw() +
#   theme(legend.position = "none", aspect.ratio = 1) +
#   facet_wrap(~direction, scales = "free") +
#   ylab("Gene counts (fpkm)") +
#   xlab("Hours post injection"))
#ggsave("Results/limma/time_top_genes_time.png", time_plot, width = 6, height = 6)
```

### Volcano plot 
```{r}
library(ggrepel)
top_time$gene_name <- rownames(top_time)

top_time_vol <- top_time %>% 
  mutate(color_2 = case_when(Hr_2.UC > 2 & P.Value < 0.05 ~ "Upregulated at 2 hrs",
                           `Hr_2.UC` < -2 & P.Value < 0.05 ~ "Downregulated at 2 hrs",
                           TRUE ~ "NS"),
         color_4 = case_when(Hr_4.Hr_2 > 2 & P.Value < 0.05 ~ "Upregulated at 4 hrs",
                           Hr_4.Hr_2 < -2 & P.Value < 0.05 ~ "Downregulated at 4 hrs",
                           TRUE ~ "NS"))

colors_time <- c("#F56B5C", "#FEC287", "#000004")

(time_volcano_2 <- top_time_vol %>% 
  filter(Hr_2.UC <10000) %>% 
  ggplot(aes(x = Hr_2.UC, y = -log10(P.Value), label = gene_name)) +
  geom_point(aes(color = color_2)) +
  geom_text_repel(data = top_time_vol %>% filter(!color_2 == "NS"), aes(label = gene_name)) +
  scale_color_manual(values = c("#000004", "lightgrey", "#FEC287"), name = NULL) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  xlab("Log2 Fold Change at 2 hours") +
  ylab("-log10(P value)") +
  ggtitle("Genes differentially expressed in hemocytes \n(2 hours post injection versus uninfected)"))

(time_volcano_4 <- top_time_vol %>% 
  ggplot(aes(x = `Hr_4.Hr_2`, y = -log10(P.Value), label = gene_name)) +
  geom_point(aes(color = color_4)) +
  geom_text_repel(data = top_time_vol %>% filter(!color_4 == "NS"), aes(label = gene_name)) +
  scale_color_manual(values = c("#000004", "lightgrey", "#F56B5C"), name = NULL) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  xlab("Log2 Fold Change at 4 hours") +
  ylab("-log10(P value)") +
  ggtitle("Genes differentially expressed in hemocytes \n(4 hours post injection versus 2 hours post injection)"))
  
# ggsave("results/volcano_2hr.png", time_volcano_2, width = 6, height = 4)  
# ggsave("results/volcano_4hr.png", time_volcano_4, width = 6, height = 4)
```



# ClusterProfiler GSEA
## 2 hr
```{r}
top_dif_gsea <- top_dif %>% 
  mutate(gene = rownames(.)) %>% 
  left_join(gene_names_fb, by = c("gene" = "gene_name"))
original_gene_list <- top_dif_gsea$dif2hr
names(original_gene_list) <- (top_dif_gsea$gene_id)
gene_list <- na.omit(original_gene_list)
gene_list <- sort(gene_list, decreasing = TRUE)

gse <- gseGO(geneList = gene_list,
             ont = "ALL",
             keyType = "FLYBASE",
             minGSSize = 3,
             maxGSSize = 800,
             pvalueCutoff = 0.05,
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "none")

gse_both_2hr <- gse
```

```{r}
require(DOSE)

direction_labs <- c("Up-regulated", "Down-regulated")
names(direction_labs) <- c("activated", "suppressed")


(gse_both_2hr_dotplot <- dotplot(gse_both_2hr, showCategory=10, split=".sign") +
  facet_grid(.~.sign, labeller = labeller(.sign = direction_labs)) +
  theme(strip.background = element_rect(fill = "white")) +
  ggtitle("Enriched GO terms differentially regulated in hemocytes 2 hours post injection"))
#ggsave("Results/limma/gse_both_2hr_dotplot.png", plot = gse_both_2hr_dotplot, width = 14, height = 6) 
```
 
### KEGG
```{r}
# We will lose some genes here because not all IDs will be converted
ids<-bitr(names(original_gene_list), fromType = "FLYBASE", toType = "ENTREZID", OrgDb=organism)
 # remove duplicate IDS (here I use "ENSEMBL", but it should be whatever was selected as keyType)
dedup_ids = ids[!duplicated(ids[c("FLYBASE")]),]

df2 = top_dif_gsea[top_dif_gsea$gene_id %in% dedup_ids$FLYBASE,]
df2$Y = dedup_ids$ENTREZID
kegg_gene_list <- df2$dif2hr
names(kegg_gene_list) <- df2$Y
kegg_gene_list<-na.omit(kegg_gene_list)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)

kegg_organism = "dme"
kegg_dif_2hr <- gseKEGG(geneList     = kegg_gene_list,
               organism     = kegg_organism,
               nPerm        = 10000,
               minGSSize    = 3,
               maxGSSize    = 800,
               pvalueCutoff = 0.05,
               pAdjustMethod = "none",
               keyType       = "ncbi-geneid")

direction_labs <- c("Positive fold-change", "Negative fold-change")
names(direction_labs) <- c("activated", "suppressed")



(gse_kegg_both_2hr_dotplot <- dotplot((kegg_dif_2hr %>% filter(Description %in% c("Endocytosis", "Phagosome", "Toll and Imd signaling pathway"))), showCategory=10, split=".sign") +
  facet_grid(.~.sign, labeller = labeller(.sign = direction_labs)) +
  theme(strip.background = element_rect(fill = "white"), aspect.ratio = 1) +
  ggtitle("Enriched KEGG pathways differentially \nregulated in hemocytes 2 hours post injection"))
#ggsave("results/gse_kegg_both_2hr_dotplot.png", plot = gse_kegg_both_2hr_dotplot, width = 7, height = 5) 
```

## 4 hr
```{r}
original_gene_list <- top_dif_gsea$dif4hr
names(original_gene_list) <- top_dif_gsea$gene_id
gene_list <- na.omit(original_gene_list)
gene_list <- sort(gene_list, decreasing = TRUE)

gse <- gseGO(geneList = gene_list,
             ont = "ALL",
             keyType = "FLYBASE",
             minGSSize = 3,
             maxGSSize = 800,
             pvalueCutoff = 0.05,
             verbose = TRUE,
             OrgDb = organism,
             pAdjustMethod = "none")

gse_both_4hr <- gse
```

```{r}
require(DOSE)

direction_labs <- c("Up-regulated", "Down-regulated")
names(direction_labs) <- c("activated", "suppressed")

(gse_both_4hr_dotplot <- dotplot(gse_both_4hr, showCategory=10, split=".sign") +
  facet_grid(.~.sign, labeller = labeller(.sign = direction_labs)) +
  theme(strip.background = element_rect(fill = "white")) +
  ggtitle("Enriched GO terms differentially regulated in hemocytes 4 hours post injection"))
#ggsave("Results/limma/gse_both_4hr_dotplot.png", plot = gse_both_4hr_dotplot, width = 14, height = 6) 
```
 
### KEGG
```{r}
# We will lose some genes here because not all IDs will be converted
ids<-bitr(names(original_gene_list), fromType = "FLYBASE", toType = "ENTREZID", OrgDb=organism)
 # remove duplicate IDS (here I use "ENSEMBL", but it should be whatever was selected as keyType)
dedup_ids = ids[!duplicated(ids[c("FLYBASE")]),]

df2 = top_dif_gsea[top_dif_gsea$gene_id %in% dedup_ids$FLYBASE,]
df2$Y = dedup_ids$ENTREZID
kegg_gene_list <- df2$dif4hr
names(kegg_gene_list) <- df2$Y
kegg_gene_list<-na.omit(kegg_gene_list)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)

kegg_organism = "dme"
kegg_dif_4hr <- gseKEGG(geneList     = kegg_gene_list,
               organism     = kegg_organism,
               nPerm        = 10000,
               minGSSize    = 3,
               maxGSSize    = 800,
               pvalueCutoff = 0.05,
               pAdjustMethod = "none",
               keyType       = "ncbi-geneid")

direction_labs <- c("Positive fold-change", "Negative fold-change")
names(direction_labs) <- c("activated", "suppressed")

(gse_kegg_both_4hr_dotplot <- dotplot((kegg_dif_4hr %>% filter(Description %in% c("Endocytosis", "Phagosome", "Toll and Imd signaling pathway"))), showCategory=10, split=".sign") +
  facet_grid(.~.sign, labeller = labeller(.sign = direction_labs)) +
  theme(strip.background = element_rect(fill = "white"), aspect.ratio = 1) +
  ggtitle("Enriched KEGG pathways differentially \nregulated in hemocytes 4 hours post injection"))
#ggsave("results/gse_kegg_both_4hr_dotplot.png", plot = gse_kegg_both_4hr_dotplot, width = 7, height = 5) 

```


## Looking at dimorphic pathways 
```{r}
toll_imd_pathway <- kegg_dif_2hr@geneSets$dme04624
endocytosis <- kegg_dif_2hr@geneSets$dme04144
phagosome <- kegg_dif_2hr@geneSets$dme04145
aminoacyle_bio <- kegg_dif_2hr@geneSets$dme00970
mapk <- kegg_dif_2hr@geneSets$dme04013
ox_phos <- kegg_dif_2hr@geneSets$dme00190
globo_isoglobo <- kegg_dif_2hr@geneSets$dme00603
ganglio <- kegg_dif_2hr@geneSets$dme00604
hippo <- kegg_dif_2hr@geneSets$dme04391
histidine <- kegg_dif_2hr@geneSets$dme00340
processing <- kegg_dif_2hr@geneSets$dme04141
glycan <- kegg_dif_2hr@geneSets$dme00511
```

### Toll and Imd
```{r}
toll_imd_ids<-bitr(toll_imd_pathway, fromType = "ENTREZID", toType = "FLYBASE", OrgDb=organism)
toll_imd_top_dif <- fpkm_counts %>% 
  filter(gene_id %in% toll_imd_ids$FLYBASE) %>% 
  select(contains("hem"))

library(heatmap3)
library(viridis)
library(gridGraphics)
colors <- colorRampPalette( viridis(9) )(28236)


mat_top_toll_imd <- as.matrix(toll_imd_top_dif)

mat_top_toll_imd <- mat_top_toll_imd - rowMeans(mat_top_toll_imd)

heatmap3(mat_top_toll_imd, trace = "none", col = colors, labCol = NULL, labRow = rownames(mat_top_toll_imd), RowSideLabs = F, ColSideLabs = F, mar = c(5, 12), key.title = "Expression", cexRow = 1, scale = "row")
# grid.echo()
# top_toll_imd <- grid.grab()
# 
# png(filename = "Results/top_toll_imd.png", width = 1000, height = 1200, units = "px")
# grid.draw(top_toll_imd)s
# dev.off()
toll_imd_mod <- top_dif_gsea %>% 
  filter(gene_id %in% toll_imd_ids$FLYBASE) %>% 
  mutate(direction = case_when(dif2hr > 0 ~ "Positive",
                               dif2hr < 0 ~ "Negative"))

gg_toll_imd <- as.data.frame(mat_top_toll_imd) %>% 
  mutate(gene = rownames(mat_top_toll_imd)) %>% 
  left_join(toll_imd_mod, by = "gene") %>% 
  pivot_longer(cols = 1:27, names_to = "sample", values_to = "count") %>% 
  separate(sample, into = c("Sex", "Time", "hem", "rep")) %>% 
  mutate(time_hours = case_when(Time == "2h" ~ 2,
                                Time == "4h" ~ 4,
                                Time == "UC" ~ 0)) %>% 
  group_by(time_hours, Sex, gene) %>% 
  mutate(avg_count = mean(count))

direction_labs <- c("Negative fold-change", "Positive fold-change")
names(direction_labs) <- c("Negative", "Positive")

sex_labs <- c("Female", "Male")
names(sex_labs) <- c("F", "M")

(toll_imd_plot <- ggplot(gg_toll_imd, aes(x = time_hours, y = count, color = gene, fill = gene)) +
  geom_smooth() +
  geom_point() +
  theme_bw() +
  theme(legend.position = "none", aspect.ratio = 1) +
  facet_grid(direction~Sex, labeller = labeller(direction = direction_labs, Sex = sex_labs)) +
  ylab("Gene counts (normalized to zero)") +
  xlab("Hours post injection") +
  ggtitle("Expression of Toll and Imd pathway in hemocytes") +
  theme(aspect.ratio = 1, strip.background = element_rect(fill = "white")))
ggsave("results/toll_imd_plot.png", plot = toll_imd_plot, width = 5, height = 5) 


############################################################
# Non-stratified by sex
toll_imd_top_dif <- fpkm_counts %>% 
  filter(gene_id %in% toll_imd_ids$FLYBASE) %>% 
  select(contains("hem"))



toll_imd_vol <- top_time_vol %>% 
  left_join(gene_names_fb) %>% 
  filter(gene_id %in% toll_imd_ids$FLYBASE) 


(toll_imd_vol_plot <- ggplot(toll_imd_vol, aes(x = `Hr_2.UC`, y = -log10(P.Value), label = gene_name)) +
    geom_point(aes(color = color_2)) +
    geom_text_repel(data = toll_imd_vol %>% filter(!color_2 == "NS")) +
    scale_color_manual(values = c("#000004", "lightgrey", "#FEC98D"), name = NULL) +
    theme_bw() +
    xlab("Log2 Fold Change at 2 hours") +
    ylab("-log10(P value)") +
    ggtitle(paste("Change in Toll and Imd pathways \nafter 2 hours")) +
    theme(aspect.ratio = 1))

(toll_imd_vol_4_plot <- ggplot(toll_imd_vol, aes(x = Hr_4.Hr_2, y = -log10(P.Value), label = gene_name)) +
    geom_point(aes(color = color_4)) +
    geom_text_repel(data = toll_imd_vol %>% filter(!color_4 == "NS")) +
    scale_color_manual(values = c("#000004", "lightgrey", "#F56B5C"), name = NULL) +
    theme_bw() +
    xlab("Log2 Fold Change at 4 hours") +
    ylab("-log10(P value)") +
    ggtitle(paste("Change in Toll and Imd pathways \nbetween 4 and 2 hours")) +
    theme(aspect.ratio = 1))

ggsave("results/toll_imd_vol_2.png", toll_imd_vol_plot, width = 6, height = 4)
ggsave("results/toll_imd_vol_4.png", toll_imd_vol_4_plot, width = 6, height = 4)



############################
# Sex-specific per time
toll_imd_vol_0 <- top_sex_0 %>% 
  mutate(gene_name = rownames(.)) %>% 
  left_join(gene_names_fb) %>% 
  filter(gene_id %in% toll_imd_ids$FLYBASE) %>% 
  mutate(colors = case_when(logFC > 1.5 & P.Value < 0.05 ~ "Male-specific",
                            logFC < -1.5 & P.Value < 0.05 ~ "Female-specific",
                            TRUE ~ "NS"))


(toll_imd_vol_plot_0 <- ggplot(toll_imd_vol_0, aes(x = logFC, y = -log10(P.Value), label = gene_name)) +
    geom_point(aes(color = colors)) +
    geom_text_repel(data = toll_imd_vol_0 %>% filter(!colors == "NS")) +
    scale_color_manual(values = c("#D3C164", "#05366E", "lightgrey"), name = NULL) +
    theme_bw() +
    xlab("Log2 Fold Change at baseline") +
    ylab("-log10(P value)") +
    ggtitle(paste("Sex specific expression of Toll and Imd pathways after 0 hours")) +
    theme(aspect.ratio = 1))

toll_imd_vol_2 <- top_sex_2 %>% 
  mutate(gene_name = rownames(.)) %>% 
  left_join(gene_names_fb) %>% 
  filter(gene_id %in% toll_imd_ids$FLYBASE) %>% 
  mutate(colors = case_when(logFC > 1.5 & P.Value < 0.05 ~ "Male-specific",
                            logFC < -1.5 & P.Value < 0.05 ~ "Female-specific",
                            TRUE ~ "NS"))


(toll_imd_vol_plot_2 <- ggplot(toll_imd_vol_2, aes(x = logFC, y = -log10(P.Value), label = gene_name)) +
    geom_point(aes(color = colors)) +
    geom_text_repel(data = toll_imd_vol_2 %>% filter(!colors == "NS")) +
    scale_color_manual(values = c("#D3C164", "#05366E", "lightgrey"), name = NULL) +
    theme_bw() +
    xlab("Log2 Fold Change at 2 hours") +
    ylab("-log10(P value)") +
    ggtitle(paste("Sex specific expression of Toll and Imd pathways after 2 hours")) +
    theme(aspect.ratio = 1))

toll_imd_vol_4 <- top_sex_4 %>% 
  mutate(gene_name = rownames(.)) %>% 
  left_join(gene_names_fb) %>% 
  filter(gene_id %in% toll_imd_ids$FLYBASE) %>% 
  mutate(colors = case_when(logFC > 1.5 & P.Value < 0.05 ~ "Male-specific",
                            logFC < -1.5 & P.Value < 0.05 ~ "Female-specific",
                            TRUE ~ "NS"))


(toll_imd_vol_plot_4 <- ggplot(toll_imd_vol_4, aes(x = logFC, y = -log10(P.Value), label = gene_name)) +
    geom_point(aes(color = colors)) +
    geom_text_repel(data = toll_imd_vol_4 %>% filter(!colors == "NS")) +
    scale_color_manual(values = c("#D3C164", "#05366E", "lightgrey"), name = NULL) +
    theme_bw() +
    xlab("Log2 Fold Change at 4 hours") +
    ylab("-log10(P value)") +
    ggtitle(paste("Sex specific expression of Toll and Imd pathways after 4 hours")) +
    theme(aspect.ratio = 1))

ggsave("results/toll_imd_vol_plot_0.png", toll_imd_vol_plot_0, width = 6, height = 4)
ggsave("results/toll_imd_vol_plot_2.png", toll_imd_vol_plot_2, width = 6, height = 4)
ggsave("results/toll_imd_vol_plot_4.png", toll_imd_vol_plot_4, width = 6, height = 4)

```

##### Endocytosis
```{r}
endocytosis_ids<-bitr(endocytosis, fromType = "ENTREZID", toType = "FLYBASE", OrgDb=organism)
endocytosis_top_dif <- fpkm_counts %>% 
  filter(gene_id %in% endocytosis_ids$FLYBASE) %>% 
  select(contains("hem"))

library(heatmap3)
library(viridis)
library(gridGraphics)
colors <- colorRampPalette( viridis(9) )(28236)


mat_endocytosis_top_dif <- as.matrix(endocytosis_top_dif)

mat_endocytosis_top_dif <- mat_endocytosis_top_dif - rowMeans(mat_endocytosis_top_dif)

# heatmap3(mat_endocytosis_top_dif, trace = "none", col = colors, labCol = NULL, labRow = rownames(mat_endocytosis_top_dif), RowSideLabs = F, ColSideLabs = F, mar = c(5, 12), key.title = "Expression", cexRow = 1, scale = "row")
# grid.echo()
# top_endocytosis <- grid.grab()
# 
# png(filename = "Results/heatmap_endocytosis.png", width = 1000, height = 1200, units = "px")
# grid.draw(top_endocytosis)
# dev.off()


endocytosis_mod <- top_dif_gsea %>% 
  filter(gene_id %in% endocytosis_ids$FLYBASE) %>% 
  mutate(direction = case_when(dif2hr > 0 ~ "Positive",
                               dif2hr < 0 ~ "Negative"))

gg_endocytosis <- as.data.frame(mat_endocytosis_top_dif) %>% 
  mutate(gene = rownames(mat_endocytosis_top_dif)) %>% 
  left_join(endocytosis_mod, by = "gene") %>% 
  pivot_longer(cols = 1:27, names_to = "sample", values_to = "count") %>% 
  separate(sample, into = c("Sex", "Time", "hem", "rep")) %>% 
  mutate(time_hours = case_when(Time == "2h" ~ 2,
                                Time == "4h" ~ 4,
                                Time == "UC" ~ 0)) %>% 
  group_by(time_hours, Sex, gene) %>% 
  mutate(avg_count = mean(count))

direction_labs <- c("Negative fold-change", "Positive fold-change")
names(direction_labs) <- c("Negative", "Positive")

sex_labs <- c("Female", "Male")
names(sex_labs) <- c("F", "M")

(endocytosis_plot <- ggplot(gg_endocytosis, aes(x = time_hours, y = count, color = gene, fill = gene)) +
  geom_smooth() +
  geom_point() +
  theme_bw() +
  theme(legend.position = "none", aspect.ratio = 1) +
  facet_grid(direction~Sex, labeller = labeller(direction = direction_labs, Sex = sex_labs)) +
  ylab("Gene counts (normalized to zero)") +
  xlab("Hours post injection") +
  ggtitle("Expression of endocytosis pathway in hemocytes") +
  theme(aspect.ratio = 1, strip.background = element_rect(fill = "white")))
#ggsave("results/endocytosis_plot.png", plot = endocytosis_plot, width = 5, height = 5) 


############################################################
# Non-stratified by sex


endo_vol <- top_time_vol %>% 
  left_join(gene_names_fb) %>% 
  filter(gene_id %in% endocytosis_ids$FLYBASE) 


(endo_vol_plot <- ggplot(endo_vol, aes(x = `Hr_2.UC`, y = -log10(P.Value), label = gene_name)) +
    geom_point(aes(color = color_2)) +
    geom_text_repel(data = endo_vol %>% filter(!color_2 == "NS")) +
    scale_color_manual(values = c("#000004", "lightgrey", "#FEC98D"), name = NULL) +
    theme_bw() +
    xlab("Log2 Fold Change at 2 hours") +
    ylab("-log10(P value)") +
    ggtitle(paste("Change in endocytosis pathways after 2 hours")) +
    theme(aspect.ratio = 1))

(endo_vol_4_plot <- ggplot(endo_vol, aes(x = Hr_4.Hr_2, y = -log10(P.Value), label = gene_name)) +
    geom_point(aes(color = color_4)) +
    geom_text_repel(data = endo_vol %>% filter(!color_4 == "NS")) +
    scale_color_manual(values = c("#000004", "lightgrey", "#F56B5C"), name = NULL) +
    theme_bw() +
    xlab("Log2 Fold Change at 4 hours") +
    ylab("-log10(P value)") +
    ggtitle(paste("Change in endocytosis pathways between 4 and 2 hours")) +
    theme(aspect.ratio = 1))

# ggsave("Results/endocytosis_vol_2.png", endo_vol_plot, width = 8, height = 6)
# ggsave("Results/endocytosis_vol_4.png", endo_vol_4_plot, width = 8, height = 6)

```

##### Phagosome
```{r}
phagosome_ids<-bitr(phagosome, fromType = "ENTREZID", toType = "FLYBASE", OrgDb=organism)
phagosome_top_dif <- fpkm_counts %>% 
  filter(gene_id %in% phagosome_ids$FLYBASE) %>% 
  select(contains("hem")) %>% 
  filter(!rowMeans(.) == 0)

library(heatmap3)
library(viridis)
library(gridGraphics)
colors <- colorRampPalette( viridis(9) )(28236)


mat_phagosome_top_dif <- as.matrix(phagosome_top_dif)

mat_phagosome_top_dif <- mat_phagosome_top_dif - rowMeans(mat_phagosome_top_dif)

# heatmap3(mat_phagosome_top_dif, trace = "none", col = colors, labCol = NULL, labRow = rownames(mat_phagosome_top_dif), RowSideLabs = F, ColSideLabs = F, mar = c(5, 12), key.title = "Expression", cexRow = 1, scale = "row")
# grid.echo()
# top_phagosome <- grid.grab()
# 
# png(filename = "Results/heatmap_phagosome.png", width = 1000, height = 1200, units = "px")
# grid.draw(top_phagosome)
# dev.off()


phagosome_mod <- top_dif_gsea %>% 
  filter(gene_id %in% phagosome_ids$FLYBASE) %>% 
  mutate(direction = case_when(dif2hr > 0 ~ "Positive",
                               dif2hr < 0 ~ "Negative"))

gg_phagosome <- as.data.frame(mat_phagosome_top_dif) %>% 
  mutate(gene = rownames(mat_phagosome_top_dif)) %>% 
  left_join(phagosome_mod, by = "gene") %>% 
  pivot_longer(cols = 1:27, names_to = "sample", values_to = "count") %>% 
  separate(sample, into = c("Sex", "Time", "hem", "rep")) %>% 
  mutate(time_hours = case_when(Time == "2h" ~ 2,
                                Time == "4h" ~ 4,
                                Time == "UC" ~ 0)) %>% 
  group_by(time_hours, Sex, gene) %>% 
  mutate(avg_count = mean(count))

direction_labs <- c("Negative fold-change", "Positive fold-change")
names(direction_labs) <- c("Negative", "Positive")

sex_labs <- c("Female", "Male")
names(sex_labs) <- c("F", "M")

(phagosome_plot <- ggplot(gg_phagosome, aes(x = time_hours, y = count, color = gene, fill = gene)) +
  geom_smooth() +
  geom_point() +
  theme_bw() +
  theme(legend.position = "none", aspect.ratio = 1) +
  facet_grid(direction~Sex, labeller = labeller(direction = direction_labs, Sex = sex_labs)) +
  ylab("Gene counts (normalized to zero)") +
  xlab("Hours post injection") +
  ggtitle("Expression of phagosome pathway in hemocytes") +
  theme(aspect.ratio = 1, strip.background = element_rect(fill = "white")))
#ggsave("Results/phagosome_plot.png", plot = phagosome_plot, width = 5, height = 5) 
```

###### Differences in pathway at 0
```{r}
colors_vol <- c(colors_sex, "darkgrey")
top_sex_0_vol <- top_sex_0 %>% 
  mutate(gene_name = rownames(top_sex_0)) %>% 
  left_join(gene_names_fb) %>% 
  rename(FLYBASE = gene_id) %>% 
  filter(FLYBASE %in% phagosome_ids$FLYBASE | FLYBASE %in% endocytosis_ids$FLYBASE) %>% 
  mutate(Sex_bias = case_when(logFC > 2.5 & P.Value < 0.5 ~ "Male biased",
                              logFC < -2.5 & P.Value < 0.5 ~ "Female biased",
                              TRUE ~ "NS"))

(endo_phagosome_vol_0 <- ggplot(top_sex_0_vol, aes(x = logFC, y = -log10(P.Value))) +
  geom_point(aes(color = Sex_bias)) +
  geom_text_repel(data = (top_sex_0_vol %>% filter(Sex_bias == "Female biased" | Sex_bias == "Male biased")), aes(label = gene_name)) + 
  scale_color_manual(values = colors_vol, name ="") +
  theme_bw() +
  theme(aspect.ratio = 1) +
  ggtitle("Dimorphically expressed endocytosis or phagosome \nassociated genes before challenge") +
  xlab("Log2 fold change") +
  ylab("-log10 p-value"))

ggsave("results/endo_phagosome_vol_0.png", plot = endo_phagosome_vol_0, width = 6, height = 4) 
```


## WGCNA 95%
```{r}
# Uncomment and modify the following to install any missing packages
# install.packages(c("tidyverse", "magrittr", "WGCNA"))
library(tidyverse)     # tidyverse will pull in ggplot2, readr, other useful libraries
library(magrittr)      # provides the %>% operator
library(WGCNA)   
```

```{r}
col_sel <- names(dat_fpkm_hem)

my_data <- dat_fpkm_hem %>% 
  tidyr::pivot_longer(
    .,
    col = all_of(col_sel)
  ) %>% 
  mutate(group = gsub("_hem_.", "", name))

# ==== Plot groups (Sample Groups vs RNA Seq Counts) to identify outliers
# (
#  p <- my_data %>%
#     ggplot(., aes(x = name, y = value)) +             # x = treatment, y = RNA Seq count
#     geom_violin() +                                   # violin plot, show distribution
#     geom_point(alpha = 0.2) +                         # scatter plot
#     theme_bw() +
#     theme(
#       axis.text.x = element_text(angle = 90)          # Rotate treatment text
#     ) +
#     labs(x = "Treatment Groups", y = "RNA Seq Counts") +
#     facet_grid(cols = vars(group), drop = TRUE, scales = "free_x")      # Facet by hour
# )
```

```{r}
library(DESeq2)


col_data_hem_both <- col_data %>% 
  filter(Stage == "adult" & Tissue == "hemocyte") %>% 
  mutate(Time_post_inf = factor(Time_post_inf, levels = c("UC", "2_hr", "4_hr")),
         Group = factor(paste(Sex, Time_post_inf, sep = "_"), levels = c("Female_UC", "Male_UC", "Female_2_hr", "Male_2_hr", "Female_4_hr", "Male_4_hr")))

count_data_hem_both <- dat %>% 
  dplyr::select(all_of(col_data_hem_both$ID))
matrix_count_data_hem_both <- as.matrix(count_data_hem_both)

dds <- DESeqDataSetFromMatrix(matrix_count_data_hem_both,
                              col_data_hem_both,
                              design = ~Group)
#> converting counts to integer mode
#> Warning in DESeqDataSet(se, design = design, ignoreRank): some variables in
#> design formula are characters, converting to factors

dds <- DESeq(dds)
#> estimating size factors
#> estimating dispersions
#> gene-wise dispersion estimates
#> mean-dispersion relationship
#> final dispersion estimates
#> fitting model and testing
vsd <- varianceStabilizingTransformation(dds)
library(genefilter)      # <= why is this here?
#>
#> Attaching package: 'genefilter'
#> The following objects are masked from 'package:matrixStats':
#>
#>     rowSds, rowVars
#> The following object is masked from 'package:readr':
#>
#>     spec
wpn_vsd <- getVarianceStabilizedData(dds)
rv_wpn <- rowVars(wpn_vsd)
summary(rv_wpn)
#>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.
#>  0.00000  0.00000  0.00000  0.08044  0.03322 11.14529

q75_wpn <- quantile( rowVars(wpn_vsd), .75)  # <= original
q95_wpn <- quantile( rowVars(wpn_vsd), .95)  # <= changed to 95 quantile to reduce dataset
expr_normalized <- wpn_vsd[ rv_wpn > q95_wpn, ]

expr_normalized[1:5,1:10]
#>                       B-3      B-4      B-5      L-3      L-4      L-5      S-3
#> AC149818.2_FG001 7.600901 7.077399 7.803434 7.220840 7.410408 8.028223 7.160846
#> AC149829.2_FG003 8.782014 8.179876 7.900062 8.299778 7.529891 8.631731 8.055118
#> AC182617.3_FG001 8.047244 7.120668 6.885533 7.501391 7.279413 7.809565 7.184253
#> AC186512.3_FG001 6.901539 7.389644 6.975945 6.859593 7.370816 6.633722 7.798843
#> AC186512.3_FG007 7.919688 7.754506 7.670946 7.417760 7.988427 7.904850 7.484542
#>                       S-4      S-5   B_L1.1
#> AC149818.2_FG001 7.401382 7.345322 6.524435
#> AC149829.2_FG003 8.744502 8.142909 8.240407
#> AC182617.3_FG001 8.140134 6.972400 7.777347
#> AC186512.3_FG001 6.949501 6.952659 6.059033
#> AC186512.3_FG007 8.375664 7.762799 6.335663
dim(expr_normalized)
#> [1] 5486   24

# expr_normalized_df <- data.frame(expr_normalized) %>%
#   mutate(
#     Gene_id = row.names(expr_normalized)
#   ) %>%
#   pivot_longer(-Gene_id)
# 
# expr_normalized_df %>% ggplot(., aes(x = name, y = value)) +
#   geom_violin() +
#   geom_point() +
#   theme_bw() +
#   theme(
#     axis.text.x = element_text( angle = 90)
#   ) +
#   ylim(0, NA) +
#   labs(
#     title = "Normalized and 75 quantile Expression",
#     x = "treatment",
#     y = "normalized expression"
#   )
```


```{r}
input_mat = t(expr_normalized)

input_mat[1:5,1:10]           # Look at first 5 rows and 10 columns

#library(WGCNA)
allowWGCNAThreads()          # allow multi-threading (optional)
#> Allowing multi-threading with up to 4 threads.

# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to = 20, by = 2))

# Call the network topology analysis function
sft = pickSoftThreshold(
  input_mat,             # <= Input data
  #blockSize = 30,
  powerVector = powers,
  verbose = 5
  )

par(mfrow = c(1,2));
cex1 = 0.9;

plot(sft$fitIndices[, 1],
     -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
     xlab = "Soft Threshold (power)",
     ylab = "Scale Free Topology Model Fit, signed R^2",
     main = paste("Scale independence")
)
text(sft$fitIndices[, 1],
     -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
     labels = powers, cex = cex1, col = "red"
)
abline(h = 0.90, col = "red")
plot(sft$fitIndices[, 1],
     sft$fitIndices[, 5],
     xlab = "Soft Threshold (power)",
     ylab = "Mean Connectivity",
     type = "n",
     main = paste("Mean connectivity")
)
text(sft$fitIndices[, 1],
     sft$fitIndices[, 5],
     labels = powers,
     cex = cex1, col = "red")
```


```{r}
picked_power = 18
temp_cor <- cor       
cor <- WGCNA::cor         # Force it to use WGCNA cor function (fix a namespace conflict issue)
netwk <- blockwiseModules(input_mat,                # <= input here

                          # == Adjacency Function ==
                          power = picked_power,                # <= power here
                          networkType = "signed",

                          # == Tree and Block Options ==
                          deepSplit = 2,
                          pamRespectsDendro = F,
                          # detectCutHeight = 0.75,
                          minModuleSize = 30,
                          maxBlockSize = 4000,

                          # == Module Adjustments ==
                          reassignThreshold = 0,
                          mergeCutHeight = 0.25,

                          # == TOM == Archive the run results in TOM file (saves time)
                          saveTOMs = T,
                          saveTOMFileBase = "ER",

                          # == Output Options
                          numericLabels = T,
                          verbose = 3)


cor <- temp_cor     # Return cor function to original namespace
```


```{r}
# Convert labels to colors for plotting
mergedColors = labels2colors(netwk$colors)
# Plot the dendrogram and the module colors underneath
plotDendroAndColors(
  netwk$dendrograms[[1]],
  mergedColors[netwk$blockGenes[[1]]],
  "Module colors",
  dendroLabels = FALSE,
  hang = 0.03,
  addGuide = TRUE,
  guideHang = 0.05 )
```

```{r}
module_df_95 <- data.frame(
  gene_id = names(netwk$colors),
  colors = labels2colors(netwk$colors)
)

module_df_95[1:5,]
#>            gene_id    colors
#> 1 AC149818.2_FG001      blue
#> 2 AC149829.2_FG003      blue
#> 3 AC182617.3_FG001      blue
#> 4 AC186512.3_FG001 turquoise
#> 5 AC186512.3_FG007 turquoise

# write_delim(module_df,
#            file = "Results/gene_modules.txt",
#            delim = "\t")
```


```{r}
# Get Module Eigengenes per cluster
MEs0 <- moduleEigengenes(input_mat, mergedColors)$eigengenes

# Reorder modules so similar modules are next to each other
MEs0 <- orderMEs(MEs0)
module_order = names(MEs0) %>% gsub("ME","", .)

# Add treatment names
MEs0$treatment = row.names(MEs0)

# tidy & plot data
mME = MEs0 %>%
  pivot_longer(-treatment) %>%
  mutate(
    name = gsub("ME", "", name),
    name = factor(name, levels = module_order)
  )

(module_heatmap <- mME %>% 
  filter(name %in% c("grey","yellow")) %>% 
  mutate(name = factor(name, levels = c("grey", "yellow")),
         treatment = factor(treatment, levels = c("F_UC_hem_2", "F_UC_hem_3", "F_UC_hem_4", "F_UC_hem_5", "M_UC_hem_2", "M_UC_hem_3", "M_UC_hem_5", "F_2h_hem_1", "F_2h_hem_2", "F_2h_hem_3", "F_2h_hem_4", "F_2h_hem_5", "M_2h_hem_1", "M_2h_hem_2", "M_2h_hem_3", "M_2h_hem_4", "M_2h_hem_5", "F_4h_hem_1", "F_4h_hem_2", "F_4h_hem_3", "F_4h_hem_4", "F_4h_hem_5", "M_4h_hem_1", "M_4h_hem_2", "M_4h_hem_3", "M_4h_hem_4", "M_4h_hem_5"))) %>% 
  ggplot(., aes(x=treatment, y=name, fill=value)) +
  geom_tile() +
  theme_bw() +
  scale_fill_viridis() +
  theme(axis.text.x = element_text(angle=90)) +
  labs(title = "Module-trait Relationships", y = "Modules", fill="corr"))
#ggsave("results/module_heatmap.png", module_heatmap, height = 4, width = 8)
```


```{r}
# pick out a few modules of interest here
modules_of_interest = unique(module_df_95$colors)

# Pull out list of genes in that module
submod = module_df_95 %>%
  subset(colors %in% modules_of_interest)

row.names(module_df_95) = module_df_95$gene_id

# Get normalized expression for those genes
expr_normalized[1:5,1:10]

subexpr = expr_normalized[submod$gene_id,]

submod_df = data.frame(subexpr) %>%
  mutate(
    gene_id = row.names(.)
  ) %>%
  pivot_longer(-gene_id) %>%
  mutate(
    module = module_df_95[gene_id,]$colors
  )

submod_df %>% ggplot(., aes(x=name, y=value, group=gene_id)) +
  geom_line(aes(color = module),
            alpha = 0.2) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 90)
  ) +
  facet_grid(rows = vars(module)) +
  labs(x = "treatment",
       y = "normalized expression")
```

```{r}
genes_of_interest = module_df_95 %>%
  subset(colors %in% modules_of_interest)

expr_of_interest = expr_normalized[genes_of_interest$gene_id,]
expr_of_interest[1:5,1:5]


# Only recalculate TOM for modules of interest (faster, altho there's some online discussion if this will be slightly off)
TOM = TOMsimilarityFromExpr(t(expr_of_interest),
                            power = picked_power)
#> TOM calculation: adjacency..
#> ..will use 4 parallel threads.
#>  Fraction of slow calculations: 0.000000
#> ..connectivity..
#> ..matrix multiplication (system BLAS)..
#> ..normalization..
#> ..done.

# Add gene names to row and columns
row.names(TOM) = row.names(expr_of_interest)
colnames(TOM) = row.names(expr_of_interest)

edge_list = data.frame(TOM) %>%
  mutate(
    gene1 = row.names(.)
  ) %>%
  pivot_longer(-gene1) %>%
  dplyr::rename(gene2 = name, correlation = value) %>%
  unique() %>%
  subset(!(gene1==gene2)) %>%
  mutate(
    module1 = module_df_95[gene1,]$colors,
    module2 = module_df_95[gene2,]$colors
  )

head(edge_list)

write_delim(edge_list,
             file = "results/edgelist.csv",
             delim = ",")
```

#### Clusterprofiler 95

```{r}
KEGG_enrichment_95 <- vector("list")

modules <- unique(module_df_95$colors)

for(i in modules){
  genes <- module_df_95 %>% 
    filter(colors == i)

original_gene_list <- genes$colors
names(original_gene_list) <- genes$gene_id

ids<-bitr(names(original_gene_list), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=organism)
 # remove duplicate IDS (here I use "ENSEMBL", but it should be whatever was selected as keyType)
dedup_ids = ids[!duplicated(ids[c("SYMBOL")]),]

gene <- dedup_ids$ENTREZID

kk <- enrichKEGG(gene = gene,
                 organism = "dme",
                 keyType = "ncbi-geneid",
                 pvalueCutoff = 0.05)

KEGG_enrichment_95[[i]] <- kk
}

```



```{r}
dotplots <- vector("list")

for(i in modules){
  kk <- KEGG_enrichment_95[[i]]
  dotplot_graph <- dotplot(kk) + ggtitle(paste("KEGG enrichment in", i, "module"))
  dotplots[[i]] <- dotplot_graph
  if(nrow(dotplot_graph[["data"]]) > 0){
  ggsave(filename = paste("results/",i, ".png", sep = ""), dotplot_graph, width = 8, height = 6)}
}
```

### Module volcano plots
```{r}
volcanos_2_F <- vector("list")
volcanos_2_M <- vector("list")
volcanos_4_F <- vector("list")
volcanos_4_M <- vector("list")

fit_both_vol <- top_time %>% 
  mutate(color_2 = case_when(Hr_2.UC > 2 & P.Value < 0.05 ~ "Upregulated at 2 hrs",
                             Hr_2.UC < -2 & P.Value < 0.05 ~ "Downregulated at 2 hrs",
                           TRUE ~ "NS"),
         color_4 = case_when(`Hr_4.Hr_2` > 2 & P.Value < 0.05 ~ "Upregulated at 4 hrs",
                           `Hr_4.Hr_2` < -2 & P.Value < 0.05 ~ "Downregulated at 4 hrs",
                           TRUE ~ "NS"))

  yellow_genes <- module_df_95 %>% 
    filter(colors == "yellow")
  
  vol_dt <- fit_both_vol %>% 
    filter(gene %in% yellow_genes$gene_id)
  
  (yellow_volcano_2 <- ggplot(vol_dt, aes(x = Hr_2.UC, y = -log10(P.Value), label = gene)) +
    geom_point(aes(color = color_2)) +
    geom_text_repel(data = vol_dt %>% filter(!color_2 == "NS")) +
    scale_color_manual(values = c("lightgrey", "#FEC98D"), name = NULL) +
    theme_bw() +
    theme(aspect.ratio = 1) +
    xlab("Log2 Fold Change at 2 hours") +
    ylab("-log10(P value)") +
    ggtitle(paste("Genes from yellow module")))
#ggsave("results/yellow_vol.png", yellow_volcano_2, height = 4, width = 5)  
  
  (yellow_volcano_4 <- ggplot(vol_dt, aes(x = Hr_4.Hr_2, y = -log10(P.Value), label = gene)) +
    geom_point(aes(color = color_4)) +
    geom_text_repel(data = vol_dt %>% filter(!color_4 == "NS")) +
    scale_color_manual(values = c("#000004", "lightgrey", "#E65164"), name = NULL) +
    theme_bw() +
    theme(aspect.ratio = 1) +
    xlab("Log2 Fold Change at 4 hours") +
    ylab("-log10(P value)") +
    ggtitle(paste("Genes from yellow module")))
#ggsave("results/yellow_vol_4.png", yellow_volcano_4, height = 4, width = 5)  
  
    grey_genes <- module_df_95 %>% 
    filter(colors == "grey")
  
  vol_dt <- fit_both_vol %>% 
    filter(gene %in% grey_genes$gene_id)
  
  (grey_volcano_2 <- ggplot(vol_dt, aes(x = Hr_2.UC, y = -log10(P.Value), label = gene)) +
    geom_point(aes(color = color_2)) +
    geom_text_repel(data = vol_dt %>% filter(!color_2 == "NS")) +
    scale_color_manual(values = c("#000004", "lightgrey"), name = NULL) +
    theme_bw() +
    theme(aspect.ratio = 1) +
    xlab("Log2 Fold Change at 2 hours") +
    ylab("-log10(P value)") +
    ggtitle(paste("Genes from grey module")))
#ggsave("results/grey_vol.png", grey_volcano_2, height = 4, width = 5)  
  
  (grey_volcano_4 <- ggplot(vol_dt, aes(x = Hr_4.Hr_2, y = -log10(P.Value), label = gene)) +
    geom_point(aes(color = color_4)) +
    geom_text_repel(data = vol_dt %>% filter(!color_4 == "NS")) +
    scale_color_manual(values = c("#000004", "lightgrey", "#E65164"), name = NULL) +
    theme_bw() +
    theme(aspect.ratio = 1) +
    xlab("Log2 Fold Change at 4 hours") +
    ylab("-log10(P value)") +
    ggtitle(paste("Genes from grey module")))
#ggsave("results/grey_vol_4.png", grey_volcano_4, height = 4, width = 5)  
```



## Female
```{r}
top_female_vol <- top_female %>% 
  mutate(color = case_when(`Female_2.Female_0` > 2 & P.Value < 0.05 ~ "Upregulated",
                           `Female_2.Female_0` < -2 & P.Value < 0.05 ~ "Downregulated",
                           TRUE ~ "NS"))
top_female_vol$gene <- base::rownames(top_female_vol)
  

(female_volcano <- top_female_vol %>% 
 # filter(dif2hr > -2710) %>% 
 # filter(dif2hr < 1184) %>% 
  ggplot(aes(x = `Female_2.Female_0`, y = -log10(P.Value), label = gene)) +
  geom_point(aes(color = color)) +
  geom_text_repel(data = top_female_vol %>% filter(!color == "NS"), aes(label = gene)) +
  scale_color_manual(values = c("#000004", "lightgrey", "#FEC98D")) +
  theme_bw() +
  xlab("Log2 Fold Change") +
  ylab("-log10(P value)") +
  ggtitle("Genes differentially expressed in female hemocytes 2 hours after S. aureus injection"))
  
ggplotly(female_volcano)
```

## Male

```{r}
female_UC_genes <- c("Dtg", "slbo", "lin-28", "mir-4954", "CG14961", "18w", "rho", "CR44664", "ImpL2", "Plod")

gg_top_dif <- dat_fpkm_hem
colnames(gg_top_dif) <- data_colnames
gg_top_dif <- gg_top_dif %>% 
  mutate(gene = rownames(gg_top_dif)) %>% 
  filter(gene %in% female_UC_genes) %>% 
  pivot_longer(cols = 1:27, names_to = "sample", values_to = "count") %>% 
  separate(sample, into = c("Sex", "Time", "hem", "rep")) %>% 
  mutate(time_hours = case_when(Time == "2h" ~ 2,
                                Time == "4h" ~ 4,
                                Time == "UC" ~ 0)) %>% 
  group_by(Sex, time_hours, gene) %>% 
  mutate(avg_count = mean(count))

ggplot(gg_top_dif, aes(x = time_hours, y = count, color = gene, fill = gene)) +
  geom_point() +
  geom_smooth() +
  facet_grid(~Sex)+
  theme_bw() +
  theme(aspect.ratio = 1)  +
  ggtitle("Expression of genes that are most highly expressed in unchallenged females")
```


